# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: granary-demo
# version: 2
default_expiration: 1h
runtime: python37
entrypoint: gunicorn -b :$PORT app:application

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 12
  max_pending_latency: 100ms  # default is 30

handlers:
- url: /(static/bootstrap.*\.css)
  static_files: local/lib/python2.7/site-packages/oauth_dropins/\1
  upload: local/lib/python2.7/site-packages/oauth_dropins/static/bootstrap.*\.css

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /oauth_dropins/static
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/static

- url: /.+
  script: auto
  secure: always
