# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/google-container-engine/#selecting-a-base-image
      - image: google/cloud-sdk

    steps:
      - checkout

      - restore_cache:
          key: venv-2-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}

      - run:
          name: Base dependencies
          command: |
            apt-get update
            apt-get install -y python3

      - run:
          name: Python 3 dependencies
          command: |
            apt-get install -y python3-venv python3-dev
            python3 -m venv local3
            . local3/bin/activate
            pip install -U -r requirements.txt
            pip install coverage coveralls

      - run:
          name: Test Python 3
          command: |
            . local3/bin/activate
            CLOUDSDK_CORE_PROJECT=granary-demo gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
            sleep 5s
            DATASTORE_EMULATOR_HOST=localhost:8089 DATASTORE_DATASET=granary-demo python3 -m coverage run --source=. --omit=appengine_config.py,cron.py,granary/tests/\*,local3/\*,oauth-dropins/\*,old_apps/\*,setup.py,test_\*,\*_live_test.py -m unittest discover -v
            kill %1
            PYTHONPATH= python ./instagram_live_test.py --debug || true
            python -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then coveralls || true; fi

      - save_cache:
          key: venv-2-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - "local3"

      - store_artifacts:
          path: /tmp/coverage_html
