# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      # https://circleci.com/developer/orbs/orb/circleci/gcp-cli#executors-google
      - image: google/cloud-sdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-8-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            - venv-8-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - venv-8-{{ .Branch }}
            - venv-8

      - run:
          name: Install dependencies
          command: |
            pip install -U pip
            pip -V
            # make sure we install this at head, below
            pip uninstall -y oauth-dropins
            pip install -U -r requirements.txt
            pip install coverage coveralls

      - run:
          name: Run tests
          command: |
            CLOUDSDK_CORE_PROJECT=granary-demo gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
            sleep 5s
            python3 -m coverage run --source=. --omit=appengine_config.py,cron.py,granary/tests/\*,oauth-dropins/\*,old_apps/\*,setup.py,test_\*,\*_live_test.py -m unittest discover -v
            kill %1
            PYTHONPATH= python3 ./instagram_live_test.py --debug
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python3 -m coveralls || true; fi

      - save_cache:
          key: venv-8-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - "/usr/local/lib/python3.7/dist-packages/"

      - store_artifacts:
          path: /tmp/coverage_html
